### ISSUE TITLE
General Question About Paper / OSD

### ISSUE THREAD

**Issue by dephora** [crs4/ome_seadragon#37]
Hi there, 

This looks similar to something I'm working (different fields) - I'm currently using a combination of D3, OpenSeadragon, and Paper. 

I noticed in your PDF, you had regions of interest. I'm trying to solve a similar issue with interaction between Paper and the objects I draw with D3. Are you using Paper to draw ROI around objects outside of its scope?

**Comment by lucalianas** [comment]
Hi!
Yes, paper.js is the component that handles drawing over digital slides. It can draw predefined images (loaded from a DB or defined as a JSON object) and it also has interactive drawing capabilities.
In order to show ROI in the exact place over the image I placed the origin of the ** AnnotationsController** (which is a class that basically acts as a wrapper to per actual Paper viewport) on the center of the slide displayed by OpenSeadragon and added a few handler in order to automatically scale or translate Paper canvas when OpenSeadragon is resized or during the navigation phase on the slide (zoom in, zoom out, navigation in all four directions).
These bindings are defined in the **addAnnotationsController** method of the **ViewerController** class https://github.com/crs4/ome_seadragon/blob/develop/src/js/viewport_controller.js#L174 (which is, like the AnnotationsController, a wrapper for the actual OpenSeadragon object).
So, every 2D object drawn using Paper is actually in Paper's scope, everything (OpenSeadragon viewer, Paper canvas, Paper 2D objects) is wrapped by a JS API in order to provide a simple and uniform way to access objects and "mask" all the technology used to implement ome_seadragon viewer.

**Comment by dephora** [comment]
Sorry for the long delay, had to shelf that for a bit.

Really appreciate the explanation, it is an immense help.

**Comment by dephora** [comment]
Is there licensing of any sort on your tools? I'd like to use the Paper / OSD code outside of the context of OME.

**Comment by lucalianas** [comment]
Hi, the software is released under MIT license https://github.com/crs4/ome_seadragon/blob/develop/LICENSE
The backend has a strong binding with OME platform (it is basically a DZI adapter for OMERO) but the JS library should be usable with a generic system that supports OpenSeadragon DZI syntax (maybe you'll need to adapt it a little).
If you're going to use our tools or our code, please at least cite our work 😉

**Comment by dephora** [comment]
Great, yeah some modification will be needed but the core essentials are there. No problem at all with citing your work. Thanks, the tools are fantastic!
